/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import java.net.*;
import javax.swing.*;
import org.json.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Image; // ✅ tambahkan baris ini



/**
 *
 * @author ASUS
 */
public class frmCekCuaca extends javax.swing.JFrame {

    /**
     * Creates new form frmCekCuaca
     */
    public frmCekCuaca() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kota");
        model.addColumn("Suhu");
        model.addColumn("Kondisi");
        tblDataCuaca.setModel(model);

    // Muat data favorit dari file favorit.txt
        try {
            BufferedReader br = new BufferedReader(new FileReader("favorit.txt"));
            String line;
            while ((line = br.readLine()) != null) {
                cmbKota.addItem(line);
            }
            br.close();
        } catch (Exception e) {
        // abaikan jika file belum ada
    }
}    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblKota = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbKota = new javax.swing.JComboBox<>();
        btnCek = new javax.swing.JButton();
        lblKondisi = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblGambar = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnEksporCSV = new javax.swing.JButton();
        btnMuatData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataCuaca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Aplikasi Cek Cuaca Sederhana");

        lblKota.setText("Masukkan Kota : ");

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });

        jLabel3.setText("atau pilih dari daftar : ");

        cmbKota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKotaItemStateChanged(evt);
            }
        });

        btnCek.setText("Cek Cuaca");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        lblKondisi.setText("Kondisi : ");

        lblSuhu.setText("Suhu : ");

        btnSimpan.setText("Simpan Favorit");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEksporCSV.setText("Ekspor CSV");
        btnEksporCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporCSVActionPerformed(evt);
            }
        });

        btnMuatData.setText("Muat Data");
        btnMuatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuatDataActionPerformed(evt);
            }
        });

        tblDataCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kota", "Suhu", "Kondisi"
            }
        ));
        jScrollPane2.setViewportView(tblDataCuaca);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEksporCSV)
                                .addGap(18, 18, 18)
                                .addComponent(btnMuatData))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(lblKota)
                                        .addComponent(lblKondisi)
                                        .addComponent(lblSuhu))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbKota, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGap(107, 107, 107)
                                            .addComponent(lblGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKota)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCek)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKondisi)
                        .addGap(18, 18, 18)
                        .addComponent(lblSuhu))
                    .addComponent(lblGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEksporCSV)
                    .addComponent(btnMuatData))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKotaActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        try {
            String kota = txtKota.getText().trim();

            if (kota.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu!");
                return;
            }

            String apiKey = "cb3817a5c46f2ca93da2c48336fe6470"; 
            String url = "https://api.openweathermap.org/data/2.5/weather?q=" + kota + "&appid=" + apiKey + "&units=metric";

            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            con.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

        JSONObject json = new JSONObject(response.toString());
        double suhu = json.getJSONObject("main").getDouble("temp");
        String kondisi = json.getJSONArray("weather").getJSONObject(0).getString("main");

        lblSuhu.setText("Suhu : " + suhu + " °C");
        lblKondisi.setText("Kondisi : " + kondisi);

        // 🔧 Resize gambar biar proporsional
        ImageIcon icon;
        if (kondisi.equalsIgnoreCase("Clear")) {
            icon = new ImageIcon(getClass().getResource("/img/cerah.png"));
        } else if (kondisi.equalsIgnoreCase("Rain")) {
            icon = new ImageIcon(getClass().getResource("/img/hujan.png"));
        } else if (kondisi.equalsIgnoreCase("Clouds")) {
            icon = new ImageIcon(getClass().getResource("/img/berawan.png"));
        } else if (kondisi.equalsIgnoreCase("Thunderstorm")) {
            icon = new ImageIcon(getClass().getResource("/img/petir.png"));
        } else if (kondisi.equalsIgnoreCase("Mist") || kondisi.equalsIgnoreCase("Fog")) {
            icon = new ImageIcon(getClass().getResource("/img/kabut.png"));
        } else {
            icon = new ImageIcon(getClass().getResource("/img/default.png"));
        }

        // 🖼️ Ubah ukuran agar pas dengan lblGambar
        Image image = icon.getImage().getScaledInstance(lblGambar.getWidth(), lblGambar.getHeight(), Image.SCALE_SMOOTH);
        lblGambar.setIcon(new ImageIcon(image));

        // 💾 Tambahkan data ke tabel
        DefaultTableModel model = (DefaultTableModel) tblDataCuaca.getModel();
        model.addRow(new Object[]{kota, suhu + "°C", kondisi});

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data cuaca!\n" + e.getMessage());
    }


    }//GEN-LAST:event_btnCekActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try {
        String kota = txtKota.getText();
        cmbKota.addItem(kota);
        FileWriter fw = new FileWriter("favorit.txt", true);
        fw.write(kota + "\n");
        fw.close();
        JOptionPane.showMessageDialog(this, "Kota disimpan ke favorit!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan favorit!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEksporCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporCSVActionPerformed
        try {
        FileWriter fw = new FileWriter("data_cuaca.csv");
        DefaultTableModel model = (DefaultTableModel) tblDataCuaca.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            fw.write(model.getValueAt(i, 0) + "," +
                     model.getValueAt(i, 1) + "," +
                     model.getValueAt(i, 2) + "\n");
        }
        fw.close();
        JOptionPane.showMessageDialog(this, "Data cuaca berhasil disimpan ke CSV!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan CSV!");
    }

    // TODO add your handling code here:
    }//GEN-LAST:event_btnEksporCSVActionPerformed

    private void btnMuatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuatDataActionPerformed
    try {
        BufferedReader br = new BufferedReader(new FileReader("data_cuaca.csv"));
        DefaultTableModel model = (DefaultTableModel) tblDataCuaca.getModel();
        model.setRowCount(0);
        String line;
        while ((line = br.readLine()) != null) {
            model.addRow(line.split(","));
        }
        br.close();
        JOptionPane.showMessageDialog(this, "Data berhasil dimuat!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data!");
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMuatDataActionPerformed

    private void cmbKotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKotaItemStateChanged
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        txtKota.setText(cmbKota.getSelectedItem().toString());
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_cmbKotaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCekCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnEksporCSV;
    private javax.swing.JButton btnMuatData;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKota;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKondisi;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JTable tblDataCuaca;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
